# Use a Node.js base image
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Copy the server code
COPY . .

RUN npm install

# Expose the port
EXPOSE 8000

# Start the server
CMD ["npm", "start"]